//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThaoPhuong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TDONHANG()
        {
            this.DANHs = new HashSet<DANH>();
            this.TDONHANGCHITIETs = new HashSet<TDONHANGCHITIET>();
            this.TTHANHTOANCHITIETs = new HashSet<TTHANHTOANCHITIET>();
        }
    
        public string ID { get; set; }
        public Nullable<int> LOAI { get; set; }
        public string DQUAYID { get; set; }
        public string DKHACHHANGID { get; set; }
        public Nullable<System.DateTime> TIMECREATED { get; set; }
        public Nullable<System.DateTime> TIMEUPDATED { get; set; }
        public Nullable<decimal> TIENDUKIEN { get; set; }
        public Nullable<decimal> TIENDANHAT { get; set; }
        public Nullable<decimal> TONGCONG { get; set; }
        public Nullable<decimal> TIENCONG { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
        public string NAME { get; set; }
        public string NOTE { get; set; }
        public string TENSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANH> DANHs { get; set; }
        public virtual DKHACHHANG DKHACHHANG { get; set; }
        public virtual DQUAY DQUAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDONHANGCHITIET> TDONHANGCHITIETs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTHANHTOANCHITIET> TTHANHTOANCHITIETs { get; set; }
    }
}
