//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThaoPhuong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTHANHTOANCHITIET
    {
        public string ID { get; set; }
        public string TTHANHTOANID { get; set; }
        public string TDONHANGID { get; set; }
        public string NOTE { get; set; }
    
        public virtual TDONHANG TDONHANG { get; set; }
        public virtual TTHANHTOAN TTHANHTOAN { get; set; }
    }
}
