//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThaoPhuong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTHANHTOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TTHANHTOAN()
        {
            this.TTHANHTOANCHITIETs = new HashSet<TTHANHTOANCHITIET>();
        }
    
        public string ID { get; set; }
        public string NAME { get; set; }
        public string DKHACHHANGID { get; set; }
        public Nullable<decimal> TONGCONG { get; set; }
        public Nullable<decimal> TIENTHANHTOAN { get; set; }
        public string NOTE { get; set; }
        public Nullable<decimal> TIENHANG { get; set; }
        public Nullable<decimal> PHUPHI { get; set; }
        public Nullable<int> KETTHUC { get; set; }
        public Nullable<System.DateTime> TIMECREATED { get; set; }
        public Nullable<System.DateTime> TIMEUPDATED { get; set; }
    
        public virtual DKHACHHANG DKHACHHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTHANHTOANCHITIET> TTHANHTOANCHITIETs { get; set; }
    }
}
