//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThaoPhuong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTHUCHI
    {
        public string ID { get; set; }
        public Nullable<int> LOAI { get; set; }
        public string DKHACHHANGID { get; set; }
        public Nullable<decimal> THU { get; set; }
        public Nullable<decimal> CHI { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> TIMECREATED { get; set; }
        public Nullable<System.DateTime> TIMEUPDATED { get; set; }
    
        public virtual DKHACHHANG DKHACHHANG { get; set; }
    }
}
